sudo: required
services:
    - docker

before_install:
    - docker build -t juanjfigueira/docker-react -f Dockerfile.dev .

script:
    docker run juanjfigueira/docker-react npm run test -- --coverage